### ISSUE TITLE
Add Symfony Support

### ISSUE THREAD

**Issue by antohaby** [alexdodonov/mezon#1]
In your publication on habr.ru you mentioned that this project is easy to integrate into current projects.
I was looking for 5 years for such a lightweight framework! And finally, I found it!

But I wasn't sure how I can integrate it with Symfony, all my projects are written in Symfony but they are slow. How I can integrate it?

**Comment by alexdodonov** [comment]
Hi! I'am not good at Symphony. But I really want to help you.

I need a small timeout to do it.

You will get notification in this issue soon.

And thanks for your ticket )

**Comment by alexdodonov** [comment]
@antohaby could you please tell me what kind of Symphony support do you need?

**Comment by alexdodonov** [comment]
Looks like no extra activity needed.
