### ISSUE TITLE
[Suggestion] Reorganise code with PHP  Standarts / The Right Way

### ISSUE THREAD

**Issue by antohaby** [alexdodonov/mezon#2]
At this moment, I cannot integrate Mezon into my application.
Could you please make it compatible with modern PHP Standards? 

There is an article https://phptherightway.com/ which can help you to achieve high quality!

Please do it ASAP I need your project!

**Comment by alexdodonov** [comment]
Hi! I shall add this issue in my TODO list.

**Comment by alexdodonov** [comment]
What standards should be implemented first?
Right now I'am additing namespaces (almost done). What's next?

**Comment by antohaby** [comment]
I would recommend start reading PHP the right way. And step-by-step migrate code.

So the first step is to restructure your code within PSR-4 standard and use Composer for autoloading.

After that, you will be able to publish your framework to https://packagist.org/ so anyone will be able to use your code by including it via the composer.

Don't forget to split your code into modules. So people will be able to load only parts of it.
Then continue through PHP The right way.

**Comment by alexdodonov** [comment]
OK

**Comment by alexdodonov** [comment]
Camel-case for method names and namespaces were implemented

**Comment by alexdodonov** [comment]
Composer is next

**Comment by alexdodonov** [comment]
> I would recommend start reading PHP the right way. And step-by-step migrate code.
> 
> So the first step is to restructure your code within PSR-4 standard and use Composer for autoloading.
> 
> After that, you will be able to publish your framework to https://packagist.org/ so anyone will be able to use your code by including it via the composer.
> 
> Don't forget to split your code into modules. So people will be able to load only parts of it.
> Then continue through PHP The right way.

Composer support was added.

Hope you can use Mezon now.

And Happy New Year ))

**Comment by antohaby** [comment]
Thanks for all your changes. I see progress.

Unfortunately, mezon code is still incompatible with PSR standards.

PSR-4 is a standard for autoloading. I'd suggest using it instead of

```
    "autoload": {
        "files": ["autoloader.php"]
    }
```

**Comment by antohaby** [comment]
[PSR-1](https://www.php-fig.org/psr/psr-1/) is also required to be applied.

Don't hesitate to sneak into other open-source projects like: 
* https://github.com/symfony/symfony
* https://github.com/laravel/laravel

To get the idea of how they structure their source code

Keep up the good work! 👍

**Comment by alexdodonov** [comment]
The code is already aligned with PSR-1

**Comment by alexdodonov** [comment]
> Thanks for all your changes. I see progress.
> 
> Unfortunately, mezon code is still incompatible with PSR standards.
> 
> PSR-4 is a standard for autoloading. I'd suggest using it instead of
> 
> ```
>     "autoload": {
>         "files": ["autoloader.php"]
>     }
> ```

OK

**Comment by antohaby** [comment]
> The code is already aligned with PSR-1

Great. Now I would recommend changing code towards [PSR-12](https://www.php-fig.org/psr/psr-12/)
This will make code even more readable for php community.

`protected $Router = null;` to be honest capital letter hurts my eyes. Its common practice to name properties in camelCase.

`return ($Content);` I don't really understand why you need those braces? It's just extra characters that have no effect.

**Comment by alexdodonov** [comment]
> Thanks for all your changes. I see progress.
> 
> Unfortunately, mezon code is still incompatible with PSR standards.
> 
> PSR-4 is a standard for autoloading. I'd suggest using it instead of

done

**Comment by alexdodonov** [comment]
> Now I would recommend changing code towards [PSR-12](https://www.php-fig.org/psr/psr-12/)

The code is already aligned with the PSR12

**Comment by alexdodonov** [comment]
> `return ($Content);` I don't really understand why you need those braces? It's just extra characters that have no effect.

It is a 17 years old habit ) but fixed.

**Comment by alexdodonov** [comment]
> `protected $Router = null;` to be honest capital letter hurts my eyes. Its common practice to name properties in camelCase.

OK I shall do it

**Comment by alexdodonov** [comment]
> `protected $Router = null;` to be honest capital letter hurts my eyes. Its common practice to name properties in camelCase.

Fixed

**Comment by alexdodonov** [comment]
No response for a long time. I shall close this issue. If necessary please create another one.
